name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - pip:
    - openai
    - anthropic
    - litellm
    - sentence-transformers 
    - rank-bm25 
    - numpy

